# Site settings
title: Bobby's World
header-img: img/home-bg.png
email: rfhab2@gmail.com
copyright_name: bhabig
description: > # this means to ignore newlines until "baseurl:"
  Start the Show!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bhabig
learn_profile: bhabig
email_username: rfhab2@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
